import { Sale } from '@/types';

export const customerDemoOrders: Sale[] = [
  {
    id: "demo-1",
    invoiceNumber: "INV-2025-9001",
    customerId: "demo-customer",
    customerName: "Demo Customer",
    items: [
      {
        product: {
          id: "1",
          name: "Hammer",
          sku: "HW-001",
          category: "Hand Tools",
          brand: "Stanley",
          purchasePrice: 150,
          sellingPrice: 250,
          quantity: 45,
          reorderLevel: 10,
          supplier: 'Tools Wholesale',
          barcode: '1234567890123',
          description: 'Professional claw hammer',
          imageUrl: '/products/8.png',
          createdAt: new Date('2024-01-15'),
          updatedAt: new Date('2024-01-15'),
        },
        quantity: 2,
        discount: 50,
      },
      {
        product: {
          id: "2",
          name: "Screwdriver Set",
          sku: "HW-002", 
          category: "Hand Tools",
          brand: "Bosch",
          purchasePrice: 300,
          sellingPrice: 450,
          quantity: 30,
          reorderLevel: 15,
          supplier: 'Tools Wholesale',
          barcode: '1234567890124',
          description: 'Complete screwdriver set',
          imageUrl: '/products/7.png',
          createdAt: new Date('2024-01-15'),
          updatedAt: new Date('2024-01-15'),
        },
        quantity: 1,
        discount: 0,
      },
    ],
    subtotal: 950,
    discount: 50,
    tax: 0,
    total: 900,
    paymentMode: "cash" as const,
    cashierId: "3",
    cashierName: "Dilini Cashier",
    date: new Date("2025-10-25T14:30:00"),
    status: "completed" as const,
  },
  {
    id: "demo-2", 
    invoiceNumber: "INV-2025-9002",
    customerId: "demo-customer",
    customerName: "Demo Customer",
    items: [
      {
        product: {
          id: "5",
          name: "LED Bulb 9W",
          sku: "EL-001",
          category: "Electrical",
          brand: "Philips",
          purchasePrice: 80,
          sellingPrice: 120,
          quantity: 200,
          reorderLevel: 50,
          supplier: 'Electrical Depot',
          barcode: '1234567890127',
          description: 'Energy efficient LED bulb',
          imageUrl: '/products/4.png',
          createdAt: new Date('2024-01-15'),
          updatedAt: new Date('2024-01-15'),
        },
        quantity: 6,
        discount: 0,
      },
    ],
    subtotal: 720,
    discount: 0,
    tax: 0,
    total: 720,
    paymentMode: "card" as const,
    cashierId: "4", 
    cashierName: "Rohan Cashier",
    date: new Date("2025-10-22T11:15:00"),
    status: "completed" as const,
  },
  {
    id: "demo-3",
    invoiceNumber: "INV-2025-9003", 
    customerId: "demo-customer",
    customerName: "Demo Customer",
    items: [
      {
        product: {
          id: "3",
          name: "Electric Drill",
          sku: "PW-001",
          category: "Power Tools", 
          brand: "DeWalt",
          purchasePrice: 3500,
          sellingPrice: 5200,
          quantity: 8,
          reorderLevel: 5,
          supplier: 'Power Tools Inc',
          barcode: '1234567890125',
          description: 'Cordless electric drill',
          imageUrl: '/products/6.png',
          createdAt: new Date('2024-01-15'),
          updatedAt: new Date('2024-01-15'),
        },
        quantity: 1,
        discount: 500,
      },
    ],
    subtotal: 5200,
    discount: 500,
    tax: 0,
    total: 4700, // Free delivery (>5000 subtotal)
    paymentMode: "upi" as const,
    cashierId: "3",
    cashierName: "Dilini Cashier", 
    date: new Date("2025-10-18T09:45:00"),
    status: "completed" as const,
  },
  {
    id: "demo-4",
    invoiceNumber: "INV-2025-9004",
    customerId: "demo-customer", 
    customerName: "Demo Customer",
    items: [
      {
        product: {
          id: "4",
          name: 'Paint Brush 2"',
          sku: "PT-001",
          category: "Painting",
          brand: "Asian Paints",
          purchasePrice: 50,
          sellingPrice: 85,
          quantity: 120,
          reorderLevel: 30,
          supplier: 'Paint Supplies Co',
          barcode: '1234567890126',
          description: 'Professional paint brush',
          imageUrl: '/products/5.png',
          createdAt: new Date('2024-01-15'),
          updatedAt: new Date('2024-01-15'),
        },
        quantity: 4,
        discount: 20,
      },
      {
        product: {
          id: "7",
          name: "Measuring Tape 5M",
          sku: "HW-003",
          category: "Hand Tools",
          brand: "Stanley", 
          purchasePrice: 100,
          sellingPrice: 160,
          quantity: 55,
          reorderLevel: 20,
          supplier: 'Tools Wholesale',
          barcode: '1234567890129',
          description: 'Professional measuring tape',
          imageUrl: '/products/2.png',
          createdAt: new Date('2024-01-15'),
          updatedAt: new Date('2024-01-15'),
        },
        quantity: 2,
        discount: 0,
      },
    ],
    subtotal: 660,
    discount: 20,
    tax: 0,
    total: 1140, // 640 + 500 delivery
    paymentMode: "cash" as const,
    cashierId: "5",
    cashierName: "Sanduni Perera",
    date: new Date("2025-10-15T16:20:00"),
    status: "completed" as const,
  },
  {
    id: "demo-5",
    invoiceNumber: "INV-2025-9005",
    customerId: "demo-customer",
    customerName: "Demo Customer", 
    items: [
      {
        product: {
          id: "8",
          name: "Safety Goggles",
          sku: "SF-001",
          category: "Safety",
          brand: "3M",
          purchasePrice: 150,
          sellingPrice: 250,
          quantity: 40,
          reorderLevel: 15,
          supplier: 'Safety Equipment Co',
          barcode: '1234567890130',
          description: 'Anti-fog safety goggles',
          imageUrl: '/products/1.png',
          createdAt: new Date('2024-01-15'),
          updatedAt: new Date('2024-01-15'),
        },
        quantity: 2,
        discount: 0,
      },
    ],
    subtotal: 500,
    discount: 0,
    tax: 0,
    total: 1000, // 500 + 500 delivery
    paymentMode: "card" as const,
    cashierId: "2",
    cashierName: "Chaminda Manager",
    date: new Date("2025-10-12T13:40:00"),
    status: "completed" as const,
  },
  {
    id: "demo-6",
    invoiceNumber: "INV-2025-9006",
    customerId: "demo-customer",
    customerName: "Demo Customer",
    items: [
      {
        product: {
          id: "6",
          name: 'PVC Pipe 1"',
          sku: "PL-001",
          category: "Plumbing",
          brand: "Supreme",
          purchasePrice: 120,
          sellingPrice: 180,
          quantity: 6,
          reorderLevel: 10,
          supplier: 'Plumbing Supplies',
          barcode: '1234567890128',
          description: 'High quality PVC pipe',
          imageUrl: '/products/3.png',
          createdAt: new Date('2024-01-15'),
          updatedAt: new Date('2024-01-15'),
        },
        quantity: 3,
        discount: 50,
      },
    ],
    subtotal: 540,
    discount: 50,
    tax: 0,
    total: 990, // 490 + 500 delivery
    paymentMode: "upi" as const,
    cashierId: "4",
    cashierName: "Rohan Cashier",
    date: new Date("2025-10-08T10:20:00"),
    status: "completed" as const,
  },
  {
    id: "demo-7",
    invoiceNumber: "INV-2025-9007",
    customerId: "demo-customer",
    customerName: "Demo Customer",
    items: [
      {
        product: {
          id: "5",
          name: "LED Bulb 9W",
          sku: "EL-001",
          category: "Electrical",
          brand: "Philips",
          purchasePrice: 80,
          sellingPrice: 120,
          quantity: 200,
          reorderLevel: 50,
          supplier: 'Electrical Depot',
          barcode: '1234567890127',
          description: 'Energy efficient LED bulb',
          imageUrl: '/products/4.png',
          createdAt: new Date('2024-01-15'),
          updatedAt: new Date('2024-01-15'),
        },
        quantity: 8,
        discount: 0,
      },
    ],
    subtotal: 960,
    discount: 0,
    tax: 0,
    total: 1460, // 960 + 500 delivery
    paymentMode: "credit" as const,
    cashierId: "3",
    cashierName: "Dilini Cashier",
    date: new Date("2025-10-05T15:10:00"),
    status: "completed" as const,
  },
  {
    id: "demo-8",
    invoiceNumber: "INV-2025-9008",
    customerId: "demo-customer",
    customerName: "Demo Customer",
    items: [
      {
        product: {
          id: "1",
          name: "Hammer",
          sku: "HW-001",
          category: "Hand Tools",
          brand: "Stanley",
          purchasePrice: 150,
          sellingPrice: 250,
          quantity: 45,
          reorderLevel: 10,
          supplier: 'Tools Wholesale',
          barcode: '1234567890123',
          description: 'Professional claw hammer',
          imageUrl: '/products/8.png',
          createdAt: new Date('2024-01-15'),
          updatedAt: new Date('2024-01-15'),
        },
        quantity: 1,
        discount: 0,
      },
      {
        product: {
          id: "4",
          name: 'Paint Brush 2"',
          sku: "PT-001",
          category: "Painting",
          brand: "Asian Paints",
          purchasePrice: 50,
          sellingPrice: 85,
          quantity: 120,
          reorderLevel: 30,
          supplier: 'Paint Supplies Co',
          barcode: '1234567890126',
          description: 'Professional paint brush',
          imageUrl: '/products/5.png',
          createdAt: new Date('2024-01-15'),
          updatedAt: new Date('2024-01-15'),
        },
        quantity: 3,
        discount: 25,
      },
    ],
    subtotal: 505,
    discount: 25,
    tax: 0,
    total: 980, // 480 + 500 delivery
    paymentMode: "cash" as const,
    cashierId: "5",
    cashierName: "Sanduni Perera", 
    date: new Date("2025-09-28T12:30:00"),
    status: "completed" as const,
  },
  {
    id: "demo-9",
    invoiceNumber: "INV-2025-9009",
    customerId: "demo-customer",
    customerName: "Demo Customer",
    items: [
      {
        product: {
          id: "2",
          name: "Screwdriver Set",
          sku: "HW-002",
          category: "Hand Tools", 
          brand: "Bosch",
          purchasePrice: 300,
          sellingPrice: 450,
          quantity: 30,
          reorderLevel: 15,
          supplier: 'Tools Wholesale',
          barcode: '1234567890124',
          description: 'Complete screwdriver set',
          imageUrl: '/products/7.png',
          createdAt: new Date('2024-01-15'),
          updatedAt: new Date('2024-01-15'),
        },
        quantity: 1,
        discount: 0,
      },
      {
        product: {
          id: "5",
          name: "LED Bulb 9W",
          sku: "EL-001",
          category: "Electrical",
          brand: "Philips",
          purchasePrice: 80,
          sellingPrice: 120,
          quantity: 200,
          reorderLevel: 50,
          supplier: 'Electrical Depot',
          barcode: '1234567890127',
          description: 'Energy efficient LED bulb',
          imageUrl: '/products/4.png',
          createdAt: new Date('2024-01-15'),
          updatedAt: new Date('2024-01-15'),
        },
        quantity: 4,
        discount: 50,
      },
    ],
    subtotal: 930,
    discount: 50,
    tax: 0,
    total: 1380, // 880 + 500 delivery
    paymentMode: "card" as const,
    cashierId: "4",
    cashierName: "Rohan Cashier",
    date: new Date("2025-09-22T14:45:00"),
    status: "completed" as const,
  },
  {
    id: "demo-10",
    invoiceNumber: "INV-2025-9010",
    customerId: "demo-customer",
    customerName: "Demo Customer",
    items: [
      {
        product: {
          id: "7",
          name: "Measuring Tape 5M",
          sku: "HW-003",
          category: "Hand Tools",
          brand: "Stanley",
          purchasePrice: 100,
          sellingPrice: 160,
          quantity: 55,
          reorderLevel: 20,
          supplier: 'Tools Wholesale',
          barcode: '1234567890129',
          description: 'Professional measuring tape',
          imageUrl: '/products/2.png',
          createdAt: new Date('2024-01-15'),
          updatedAt: new Date('2024-01-15'),
        },
        quantity: 1,
        discount: 0,
      },
    ],
    subtotal: 160,
    discount: 0,
    tax: 0,
    total: 660, // 160 + 500 delivery
    paymentMode: "upi" as const,
    cashierId: "2",
    cashierName: "Chaminda Manager",
    date: new Date("2025-09-15T11:20:00"),
    status: "completed" as const,
  },
  {
    id: "demo-11",
    invoiceNumber: "INV-2025-9011",
    customerId: "demo-customer",
    customerName: "Demo Customer",
    items: [
      {
        product: {
          id: "2",
          name: "Screwdriver Set",
          sku: "HW-002",
          category: "Hand Tools",
          brand: "Bosch",
          purchasePrice: 300,
          sellingPrice: 450,
          quantity: 30,
          reorderLevel: 15,
          supplier: 'Tools Wholesale',
          barcode: '1234567890124',
          description: 'Complete screwdriver set',
          imageUrl: '/products/7.png',
          createdAt: new Date('2024-01-15'),
          updatedAt: new Date('2024-01-15'),
        },
        quantity: 1,
        discount: 0,
      },
      {
        product: {
          id: "5",
          name: "LED Bulb 9W",
          sku: "EL-001",
          category: "Electrical",
          brand: "Philips",
          purchasePrice: 80,
          sellingPrice: 120,
          quantity: 200,
          reorderLevel: 50,
          supplier: 'Electrical Depot',
          barcode: '1234567890127',
          description: 'Energy efficient LED bulb',
          imageUrl: '/products/4.png',
          createdAt: new Date('2024-01-15'),
          updatedAt: new Date('2024-01-15'),
        },
        quantity: 3,
        discount: 0,
      },
    ],
    subtotal: 810,
    discount: 0,
    tax: 0,
    total: 1310, // 810 + 500 delivery
    paymentMode: "cash" as const,
    cashierId: "3",
    cashierName: "Dilini Cashier",
    date: new Date("2025-10-26T18:30:00"),
    status: "pending" as const,
  },
];
