import { Product, Customer, Employee, Sale, Supplier, Expense, User } from '@/types';
import { getPermissionsForRole } from './permissions';

// Mock Users with permissions
export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Admin User',
    email: 'admin@hardware.com',
    role: 'admin',
    phone: '+1234567890',
    createdAt: new Date('2024-01-01'),
    permissions: getPermissionsForRole('admin'),
  },
  {
    id: '2',
    name: 'Manager User',
    email: 'manager@hardware.com',
    role: 'manager',
    phone: '+1234567891',
    createdAt: new Date('2024-01-01'),
    permissions: getPermissionsForRole('manager'),
  },
  {
    id: '3',
    name: 'Cashier User',
    email: 'cashier@hardware.com',
    role: 'cashier',
    phone: '+1234567892',
    createdAt: new Date('2024-01-01'),
    permissions: getPermissionsForRole('cashier'),
  },
];

// Mock Products
export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Hammer',
    sku: 'HW-001',
    category: 'Hand Tools',
    brand: 'Stanley',
    purchasePrice: 150,
    sellingPrice: 250,
    quantity: 45,
    reorderLevel: 10,
    supplier: 'Tools Wholesale',
    barcode: '1234567890123',
    description: 'Professional claw hammer with fiberglass handle',
    imageUrl: '/products/8.png',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Screwdriver Set',
    sku: 'HW-002',
    category: 'Hand Tools',
    brand: 'Bosch',
    purchasePrice: 300,
    sellingPrice: 450,
    quantity: 30,
    reorderLevel: 15,
    supplier: 'Tools Wholesale',
    barcode: '1234567890124',
    description: 'Complete screwdriver set with various sizes and types',
    imageUrl: '/products/7.png',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '3',
    name: 'Electric Drill',
    sku: 'PW-001',
    category: 'Power Tools',
    brand: 'DeWalt',
    purchasePrice: 3500,
    sellingPrice: 5200,
    quantity: 8,
    reorderLevel: 5,
    supplier: 'Power Tools Inc',
    barcode: '1234567890125',
    description: 'Cordless electric drill with variable speed control',
    imageUrl: '/products/6.png',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '4',
    name: 'Paint Brush 2"',
    sku: 'PT-001',
    category: 'Painting',
    brand: 'Asian Paints',
    purchasePrice: 50,
    sellingPrice: 85,
    quantity: 120,
    reorderLevel: 30,
    supplier: 'Paint Supplies Co',
    barcode: '1234567890126',
    description: 'Professional paint brush for all types of paint',
    imageUrl: '/products/5.png',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '5',
    name: 'LED Bulb 9W',
    sku: 'EL-001',
    category: 'Electrical',
    brand: 'Philips',
    purchasePrice: 80,
    sellingPrice: 120,
    quantity: 200,
    reorderLevel: 50,
    supplier: 'Electrical Depot',
    barcode: '1234567890127',
    description: 'Energy efficient LED bulb with cool white light',
    imageUrl: '/products/4.png',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '6',
    name: 'PVC Pipe 1"',
    sku: 'PL-001',
    category: 'Plumbing',
    brand: 'Supreme',
    purchasePrice: 120,
    sellingPrice: 180,
    quantity: 6,
    reorderLevel: 10,
    supplier: 'Plumbing Supplies',
    barcode: '1234567890128',
    description: 'High quality PVC pipe for plumbing applications',
    imageUrl: '/products/3.png',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '7',
    name: 'Measuring Tape 5M',
    sku: 'HW-003',
    category: 'Hand Tools',
    brand: 'Stanley',
    purchasePrice: 100,
    sellingPrice: 160,
    quantity: 55,
    reorderLevel: 20,
    supplier: 'Tools Wholesale',
    barcode: '1234567890129',
    description: 'Professional measuring tape with lock mechanism',
    imageUrl: 'https://images.unsplash.com/photo-1624536301766-3c88ad03da4a?w=400&h=400&fit=crop&crop=center',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '8',
    name: 'Safety Goggles',
    sku: 'SF-001',
    category: 'Safety',
    brand: '3M',
    purchasePrice: 150,
    sellingPrice: 250,
    quantity: 40,
    reorderLevel: 15,
    supplier: 'Safety Equipment Co',
    barcode: '1234567890130',
    description: 'Anti-fog safety goggles for eye protection',
    imageUrl: 'https://images.unsplash.com/photo-1584464491033-06628f3a6b7b?w=400&h=400&fit=crop&crop=center',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
];

// Mock Customers
export const mockCustomers: Customer[] = [
  {
    id: '1',
    name: 'Rajesh Kumar',
    phone: '+91-9876543210',
    email: 'rajesh@example.com',
    address: '123 MG Road, Bangalore',
    outstandingBalance: 0,
    loyaltyPoints: 150,
    createdAt: new Date('2024-01-10'),
    lastPurchase: new Date('2024-10-07'),
  },
  {
    id: '2',
    name: 'Priya Sharma',
    phone: '+91-9876543211',
    email: 'priya@example.com',
    address: '456 Park Street, Mumbai',
    outstandingBalance: 500,
    loyaltyPoints: 80,
    createdAt: new Date('2024-02-15'),
    lastPurchase: new Date('2024-10-05'),
  },
  {
    id: '3',
    name: 'Amit Patel',
    phone: '+91-9876543212',
    address: '789 Gandhi Nagar, Delhi',
    outstandingBalance: 1200,
    loyaltyPoints: 200,
    createdAt: new Date('2024-03-20'),
    lastPurchase: new Date('2024-10-01'),
  },
];

// Mock Employees
export const mockEmployees: Employee[] = [
  {
    id: '1',
    name: 'Admin User',
    role: 'admin',
    phone: '+91-9999999999',
    email: 'admin@hardwarestore.com',
    salary: 50000,
    joiningDate: new Date('2023-01-01'),
    isActive: true,
    attendanceStatus: 'present',
  },
  {
    id: '2',
    name: 'Suresh Manager',
    role: 'manager',
    phone: '+91-9999999998',
    email: 'suresh@hardwarestore.com',
    salary: 35000,
    joiningDate: new Date('2023-06-15'),
    isActive: true,
    attendanceStatus: 'present',
  },
  {
    id: '3',
    name: 'Kavita Cashier',
    role: 'cashier',
    phone: '+91-9999999997',
    email: 'kavita@hardwarestore.com',
    salary: 25000,
    joiningDate: new Date('2024-01-10'),
    isActive: true,
    attendanceStatus: 'present',
  },
  {
    id: '4',
    name: 'Ramesh Cashier',
    role: 'cashier',
    phone: '+91-9999999996',
    email: 'ramesh@hardwarestore.com',
    salary: 25000,
    joiningDate: new Date('2024-02-01'),
    isActive: true,
    attendanceStatus: 'leave',
  },
];

// Mock Sales
export const mockSales: Sale[] = [
  {
    id: '1',
    invoiceNumber: 'INV-2024-0001',
    customerId: '1',
    customerName: 'Rajesh Kumar',
    items: [
      {
        product: mockProducts[0],
        quantity: 2,
        discount: 0,
      },
      {
        product: mockProducts[1],
        quantity: 1,
        discount: 50,
      },
    ],
    subtotal: 950,
    discount: 50,
    tax: 135,
    total: 1035,
    paymentMode: 'card',
    cashierId: '3',
    cashierName: 'Kavita Cashier',
    date: new Date('2024-10-08'),
    status: 'completed',
  },
  {
    id: '2',
    invoiceNumber: 'INV-2024-0002',
    customerId: '2',
    customerName: 'Priya Sharma',
    items: [
      {
        product: mockProducts[2],
        quantity: 1,
        discount: 200,
      },
    ],
    subtotal: 5200,
    discount: 200,
    tax: 750,
    total: 5750,
    paymentMode: 'upi',
    cashierId: '3',
    cashierName: 'Kavita Cashier',
    date: new Date('2024-10-08'),
    status: 'completed',
  },
];

// Mock Suppliers
export const mockSuppliers: Supplier[] = [
  {
    id: '1',
    name: 'Tools Wholesale',
    contact: '+91-9876543220',
    email: 'info@toolswholesale.com',
    address: 'Industrial Area, Phase 1, Bangalore',
    products: ['1', '2', '7'],
    createdAt: new Date('2023-01-01'),
  },
  {
    id: '2',
    name: 'Power Tools Inc',
    contact: '+91-9876543221',
    email: 'sales@powertools.com',
    address: 'Electronic City, Bangalore',
    products: ['3'],
    createdAt: new Date('2023-01-01'),
  },
  {
    id: '3',
    name: 'Paint Supplies Co',
    contact: '+91-9876543222',
    email: 'contact@paintsupplies.com',
    address: 'Market Road, Mumbai',
    products: ['4'],
    createdAt: new Date('2023-01-01'),
  },
];

// Mock Expenses
export const mockExpenses: Expense[] = [
  {
    id: '1',
    category: 'Rent',
    amount: 25000,
    description: 'October 2024 Rent',
    date: new Date('2024-10-01'),
    paidBy: 'Admin User',
  },
  {
    id: '2',
    category: 'Electricity',
    amount: 3500,
    description: 'September 2024 Bill',
    date: new Date('2024-10-02'),
    paidBy: 'Admin User',
  },
  {
    id: '3',
    category: 'Salaries',
    amount: 135000,
    description: 'September 2024 Staff Salaries',
    date: new Date('2024-10-01'),
    paidBy: 'Admin User',
  },
];
